name: "Rust Cache"
description: "A GitHub Action that implements smart caching for rust/cargo projects with sensible defaults."
author: "Arpad Borsos <arpad.borsos@googlemail.com>"
inputs:
  key:
    description: "An additional key for the cache"
    required: false
  working-directory:
    description: "The working directory this action should operate in"
    required: false
  wrapper:
    description: "Defaults to setting RUSTC_WRAPPER=sccache"
    required: false
  cache-dir:
    description: "Sets the cache dir for sccache"
    required: false
  cache-size:
    description: "Sets the max cache size for sccache"
    required: false
  sccache-version:
    description: "Override the sccache version - defaults to latest"
    required: false
runs:
  using: "node12"
  main: "dist/restore/index.js"
  post: "dist/save/index.js"
  post-if: "success()"
branding:
  icon: "archive"
  color: "gray-dark"
